version: '3.8'

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-jammy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - BASE_URL=http://host.docker.internal:8080/praxis-wabner
    command: npx playwright test --reporter=list
    network_mode: host
