# Playwright Test-Image für Praxis Wabner
# Build: docker build -t praxis-tests tests/
FROM mcr.microsoft.com/playwright:v1.58.0-noble

WORKDIR /work
RUN npm init -y && npm install @playwright/test@1.58.0
